// Package wmi looks up World Manufacturer Identifiers in a snapshot of
// NHTSA's vPIC registry that is compiled into the binary, so lookups work
// with no network and no data files beside the executable.
//
// The snapshot (wmi.csv) is generated by tools/wmi-import and committed. It
// covers every WMI registered with NHTSA, which is every manufacturer whose
// vehicles are sold in the United States. Identifiers used only in other
// markets, such as a Chinese-market Tesla's LRW, are not in it.
//
// Rows are sorted by identifier, so Lookup binary-searches the embedded text
// and parses the one row it lands on. Decoding a single VIN therefore costs
// a handful of string comparisons rather than parsing 13,000 rows, and the
// package allocates nothing until it is used.
package wmi

import (
	_ "embed"
	"fmt"
	"iter"
	"strconv"
	"strings"
	"sync"
)

//go:embed wmi.csv
var snapshot string

// The column layout every row follows, as tools/wmi-import writes it.
const (
	headerLine = "wmi,manufacturer_id,manufacturer,make,vehicle_type,country"
	fieldCount = 6
)

// Entry is one registered manufacturer identifier.
type Entry struct {
	// Code is the identifier: three characters (VIN positions 1-3), or six
	// for a low-volume manufacturer (positions 1-3 followed by 12-14).
	Code string `json:"wmi"`
	// ManufacturerID is vPIC's numeric ID for the manufacturer.
	ManufacturerID int `json:"manufacturer_id"`
	// Manufacturer is the registered company name, as NHTSA spells it.
	Manufacturer string `json:"manufacturer"`
	// Make is the brand sold under the identifier, e.g. "CHEVROLET" for 1G1.
	// It is empty for six-character identifiers, and several makes sharing
	// one identifier are joined with "/".
	Make string `json:"make,omitempty"`
	// VehicleType is NHTSA's vehicle type for the identifier: "Passenger
	// Car", "Truck", "Multipurpose Passenger Vehicle (MPV)", "Motorcycle",
	// "Bus", "Trailer", "Low Speed Vehicle (LSV)", "Incomplete Vehicle" or
	// "Off-Road Vehicle".
	VehicleType string `json:"vehicle_type"`
	// Country is the manufacturer's country as registered with NHTSA. It can
	// be empty, and it is not necessarily where a given vehicle was built.
	Country string `json:"country,omitempty"`
}

// table is the embedded snapshot split into its header comments and its
// sorted rows.
type table struct {
	rows      string // the data rows, one per line, sorted by identifier
	retrieved string // the date in the header comment
}

var load = sync.OnceValue(func() table {
	var t table
	if _, rest, ok := strings.Cut(snapshot, "retrieved "); ok {
		t.retrieved, _, _ = strings.Cut(rest, ".")
	}
	rows := snapshot
	for strings.HasPrefix(rows, "#") { // header comments
		_, rows, _ = strings.Cut(rows, "\n")
	}
	header, rows, _ := strings.Cut(rows, "\n") // column names
	if strings.TrimSpace(header) != headerLine {
		// The snapshot is compiled in and covered by tests, so a bad header
		// means a broken build, not bad input.
		panic("wmi: embedded snapshot has unexpected columns: " + header)
	}
	t.rows = strings.TrimRight(rows, "\r\n")
	return t
})

// Lookup returns the registry entry for a three- or six-character
// identifier. Case does not matter.
func Lookup(code string) (Entry, bool) {
	line, ok := load().find(strings.ToUpper(code))
	if !ok {
		return Entry{}, false
	}
	e, err := parseRow(line)
	if err != nil {
		panic("wmi: embedded snapshot: " + err.Error())
	}
	return e, true
}

// ForVIN returns the registry entry for the manufacturer of a 17-character
// VIN. When position 3 is '9' the identifier has six characters, positions
// 1-3 plus 12-14 (49 CFR 565.15(a)); otherwise it is positions 1-3.
func ForVIN(vin string) (Entry, bool) {
	code := Code(vin)
	if code == "" {
		return Entry{}, false
	}
	return Lookup(code)
}

// Code returns the manufacturer identifier embedded in a 17-character VIN:
// three characters, or six when position 3 is '9'. It returns "" if vin is
// not 17 bytes long.
func Code(vin string) string {
	if len(vin) != 17 {
		return ""
	}
	if vin[2] == '9' {
		return vin[0:3] + vin[11:14]
	}
	return vin[0:3]
}

// All iterates over every entry in the snapshot, in identifier order.
func All() iter.Seq[Entry] {
	return func(yield func(Entry) bool) {
		for line := range strings.SplitSeq(load().rows, "\n") {
			if line = strings.TrimRight(line, "\r"); line == "" {
				continue
			}
			e, err := parseRow(line)
			if err != nil {
				panic("wmi: embedded snapshot: " + err.Error())
			}
			if !yield(e) {
				return
			}
		}
	}
}

// Len returns the number of identifiers in the snapshot.
var Len = sync.OnceValue(func() int {
	rows := load().rows
	if rows == "" {
		return 0
	}
	return strings.Count(rows, "\n") + 1
})

// Retrieved returns the date (YYYY-MM-DD) the snapshot was taken from vPIC.
func Retrieved() string { return load().retrieved }

// find binary-searches the sorted rows for the line whose first field is
// code. The rows are ASCII and sorted bytewise, which is the order string
// comparison uses.
func (t table) find(code string) (string, bool) {
	lo, hi := 0, len(t.rows)
	for lo < hi {
		mid := (lo + hi) / 2
		start := strings.LastIndexByte(t.rows[:mid], '\n') + 1
		end := start + strings.IndexByte(t.rows[start:], '\n')
		if end < start {
			end = len(t.rows)
		}
		line := t.rows[start:end]
		switch key, _, _ := strings.Cut(line, ","); {
		case key < code:
			lo = end + 1
		case key > code:
			hi = start
		default:
			return line, true
		}
	}
	return "", false
}

// parseRow turns one CSV row into an Entry.
func parseRow(line string) (Entry, error) {
	rec, err := splitRow(line)
	if err != nil {
		return Entry{}, fmt.Errorf("row %q: %w", line, err)
	}
	id, err := strconv.Atoi(rec[1])
	if err != nil {
		return Entry{}, fmt.Errorf("row %q: manufacturer_id: %w", line, err)
	}
	return Entry{
		Code:           rec[0],
		ManufacturerID: id,
		Manufacturer:   rec[2],
		Make:           rec[3],
		VehicleType:    rec[4],
		Country:        rec[5],
	}, nil
}

// splitRow splits one CSV row into its fields. The snapshot only ever quotes
// a field because it holds a comma, as manufacturer names do ("AMERICAN
// HONDA MOTOR CO., INC."), so this handles the subset of RFC 4180 the file
// uses and avoids the buffered reader encoding/csv would allocate per
// lookup. tools/wmi-import writes the file with encoding/csv.
func splitRow(line string) ([]string, error) {
	fields := make([]string, 0, fieldCount)
	for i := 0; i <= len(line); {
		if i < len(line) && line[i] == '"' {
			var b strings.Builder
			for i++; ; {
				j := strings.IndexByte(line[i:], '"')
				if j < 0 {
					return nil, fmt.Errorf("unterminated quote")
				}
				b.WriteString(line[i : i+j])
				i += j + 1
				if i < len(line) && line[i] == '"' { // "" is an escaped quote
					b.WriteByte('"')
					i++
					continue
				}
				break
			}
			if i < len(line) && line[i] != ',' {
				return nil, fmt.Errorf("unexpected text after a quoted field")
			}
			fields = append(fields, b.String())
			i++
			continue
		}
		j := strings.IndexByte(line[i:], ',')
		if j < 0 {
			fields = append(fields, line[i:])
			break
		}
		fields = append(fields, line[i:i+j])
		i += j + 1
	}
	if len(fields) != fieldCount {
		return nil, fmt.Errorf("%d fields, want %d", len(fields), fieldCount)
	}
	return fields, nil
}
